"use client"

const GlobalLoading = () => {
  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-50 px-4"> <div className="flex w-full max-w-md flex-col items-center"> {/* Book Animation */} <div className="relative mb-8 h-28 w-28"> {/* Outer Ring */} <div className=" absolute inset-0 rounded-full border-4 border-orange-100 " /> {/* Spinning Ring */} <div className=" absolute inset-0 animate-spin rounded-full border-4 border-transparent border-t-orange-500 border-r-orange-400 " /> {/* Book */} <div className=" absolute left-1/2 top-1/2 flex h-16 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-r-lg bg-gradient-to-br from-orange-400 to-orange-600 shadow-lg shadow-orange-200 animate-pulse " > {/* Book Page */} <div className=" absolute left-2 h-12 w-[2px] rounded-full bg-orange-200/70 " /> {/* Book Lines */} <div className="ml-2 flex flex-col gap-1"> <span className="h-1 w-6 rounded-full bg-white/80" /> <span className="h-1 w-5 rounded-full bg-white/60" /> <span className="h-1 w-6 rounded-full bg-white/40" /> </div> </div> </div> {/* Title */} <h1 className="text-2xl font-extrabold tracking-tight text-slate-800"> Loading<span className="text-orange-500">...</span> </h1> {/* Description */} <p className="mt-2 text-center text-sm text-slate-500"> Preparing your reading experience </p> {/* Progress Bar */} <div className="mt-7 h-2 w-full max-w-xs overflow-hidden rounded-full bg-orange-100"> <div className=" h-full w-1/2 rounded-full bg-gradient-to-r from-orange-400 to-orange-600 animate-[loading_1.5s_ease-in-out_infinite] " /> </div> {/* Loading Dots */} <div className="mt-5 flex items-center gap-2"> <span className=" h-2 w-2 animate-bounce rounded-full bg-orange-500 " /> <span className=" h-2 w-2 animate-bounce rounded-full bg-orange-500 [animation-delay:150ms] " /> <span className=" h-2 w-2 animate-bounce rounded-full bg-orange-500 [animation-delay:300ms] " /> </div> </div> {/* Custom Animation */} <style jsx>{` @keyframes loading { 0% { transform: translateX(-100%); } 50% { transform: translateX(100%); } 100% { transform: translateX(200%); } } `}</style> </div>
  )
}

export default GlobalLoading
